spring:
  application:
    name: retry-consumer-service

server:
  port: 9000
  ssl:
    enabled: true
    key-store: D:/Practice/Z_delete/keystore.jks
    key-store-password: skhskh
    key-store-type: PKCS12
